name: 'set-masked-env'
description: 'Set masked env variables from file'
inputs:
  filePath:
    description: 'The path of the file you would like to import as an environment variable.'
    required: true
  mask:
    description: 'Set to false if you would not like to mask.'
    default: true
runs:
  using: 'node16'
  main: 'lib/index.js'
branding:
  icon: arrow-left-circle
  color: 'yellow'