name: 'set-multi-secrets'
description: 'set multiple secrets from file'
inputs:
  path:
    description: file path
    required: true
  mask:
    description: mask env variables imported from file path
    default: false
runs:
  using: 'node16'
  main: 'lib/index.js'
