on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # このリポジトリのプライベートアクションを使用するには
      # リポジトリをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Dependencies
        run: npm install

      - name: Restore File
        run: echo ${{ secrets.FILE }} > ./.env

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        with:
          path: './.env'
      # 「hello」ステップの出力を使用する
      - name: Get the output time
        run: echo "The time was ${{ env.HELLO }}"

      - name: Get the Web time
        run: curl ${{ env.HELLO }}