on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # このリポジトリのプライベートアクションを使用するには
      # リポジトリをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Restore File
        run: echo ${{ secrets.FILE }} > ./.env

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        with:
          path: './.env'
      # 「hello」ステップの出力を使用する
      - name: Get the output time
        run: echo "The time was ${{ env.HELLO }}"

      - name: Get the Web time
        run: curl ${{ env.HELLO }}