on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # このリポジトリのプライベートアクションを使用するには
      # リポジトリをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update npm
        run: npm install -g npm

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Restore File
        run: echo ${{ secrets.FILE }} > ./.env

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        with:
          path: './.env'
      # 「hello」ステップの出力を使用する
      - name: Get the output time
        run: echo "The time was $HELLo"

      - name: Get the Web time
        run: curl $HELLO